package com.example.agendasacramental

object Himnos {
    val lista: Map<Int, String> = mapOf(
        1 to "Ya rompe el alba",
        2 to "El Espíritu de Dios",
        3 to "Ya regocijemos",
        4 to "Bandera de Sión",
        5 to "Oh Dios de Israel",
        6 to "Israel, Jesús os llama",
        7 to "Id, vosotros mensajeros",
        8 to "¿Qué es lo que vieron en las alturas?",
        9 to "Un ángel del Señor",
        10 to "Te damos, Señor, nuestras gracias",
        11 to "Dios manda a profetas",
        12 to "Pedimos hoy por ti",
        13 to "Bendice, Dios, a nuestro Profeta",
        14 to "La oración del Profeta",
        15 to "Loor al Profeta",
        16 to "Un pobre forastero",
        17 to "¡Oh, está todo bien!",
        18 to "Oh Sión, santuario de libertad",
        19 to "Por Tus dones loor cantamos",
        20 to "Gozoso día llega ya",
        21 to "¡Salve, Sión! Es tu día ilustre",
        22 to "En las cumbres de los montes",
        23 to "Bella Sión",
        24 to "El alba ya rompe",
        25 to "Jehová aparece en Su gloria",
        26 to "Hijos del Señor, venid",
        27 to "Oh Rey de reyes, ven",
        28 to "Himno de batalla de la República",
        29 to "Ven, oh día prometido",
        30 to "A Cristo Rey Jesús",
        31 to "Oh, creaciones del Señor",
        32 to "Baluarte firme es nuestro Dios",
        33 to "Honor, loor y gloria",
        34 to "Oh, Santo Dios, omnipotente ser",
        35 to "Haznos pensar en Ti, Señor",
        36 to "Padre bendito, venimos a Ti",
        37 to "Glorias cantad a Dios",
        38 to "Santos, avanzad",
        39 to "Jehová, sé nuestro guía",
        40 to "Qué firmes cimientos",
        41 to "¡Grande eres Tú!",
        42 to "Jesús es mi luz",
        43 to "Por la belleza terrenal",
        44 to "El sublime Creador",
        45 to "Oración de gratitud",
        46 to "Elevemos nuestros himnos",
        47 to "Caros niños, Dios os ama",
        48 to "Divina Luz",
        49 to "Señor, te necesito",
        50 to "Más cerca, Dios, de ti",
        51 to "Guíame, oh Salvador",
        52 to "Guíame a Ti",
        53 to "¡Oh Jesús, mi gran amor!",
        54 to "Paz, cálmense",
        55 to "Dios da valor",
        56 to "Jehová mi Pastor es",
        57 to "El amor del Salvador",
        58 to "Roca de eternidad",
        59 to "Mirad al Salvador",
        60 to "Venid a Cristo",
        61 to "Venid a Mí",
        62 to "No desmayéis, oh santos",
        63 to "Aunque colmados de pesar",
        64 to "Venid, los que a Dios amáis",
        65 to "¿Sin contestar?",
        66 to "Cuán dulce la ley de Dios",
        67 to "Si la vía es penosa",
        68 to "La fe",
        69 to "¿Dónde hallo el solaz?",
        70 to "Sé humilde",
        71 to "Más santidad dame",
        72 to "Creo en Cristo",
        73 to "Yo sé que vive mi Señor",
        74 to "Vive mi Señor",
        75 to "Testimonio",
        76 to "Tan sólo con pensar en Ti",
        77 to "Deja que el Espíritu te enseñe",
        78 to "Oh dulce, grata oración",
        79 to "La oración del alma es",
        80 to "Secreta oración",
        81 to "¿Pensaste orar?",
        82 to "Padre en los cielos",
        83 to "Entonad sagrado son",
        84 to "Dulce Tu obra es, Señor",
        85 to "El día santo del Señor",
        86 to "Nuestro bondadoso Padre",
        87 to "Cual rocío, que destila",
        88 to "Placentero nos es trabajar",
        89 to "Para siempre Dios esté con Vos",
        90 to "Padre, antes de partir",
        91 to "Al partir cantemos",
        92 to "Hemos sentido Tu amor",
        93 to "A Ti, Señor",
        94 to "Ya termina el día",
        95 to "El fuego del Espíritu",
        96 to "El ocaso viene ya",
        97 to "Ante Ti, Señor, Tu grey",
        98 to "Conmigo quédate, Señor",
        99 to "Acompáñame",
        100 to "Dios, bendícenos",
        101 to "Dios, escúchanos orar",
        102 to "Hoy con humildad te pido",
        103 to "La Santa Cena",
        104 to "Oh Dios, Eterno Padre",
        105 to "Jesús de Nazaret",
        106 to "Cuán grato es cantar loor",
        107 to "Pedimos Tu Espíritu",
        108 to "Mansos, reverentes hoy",
        109 to "Cantemos todos a Jesús",
        110 to "En memoria de Tu muerte",
        111 to "En el Calvario, en la cruz",
        112 to "El Padre tanto nos amó",
        113 to "Ya nos juntamos otra vez",
        114 to "Cristo, el Redentor, murió",
        115 to "Nos reunimos, Padre, hoy",
        116 to "Jesús, en la corte celestial",
        117 to "¡Murió! El Redentor murió",
        118 to "Asombro me da",
        119 to "En un lejano cerro fue",
        120 to "Tan humilde al nacer",
        121 to "Himno de la Pascua de Resurrección",
        122 to "Cristo ha resucitado",
        123 to "¡Regocijad! Jesús nació",
        124 to "Venid, adoremos",
        125 to "Jesús en pesebre",
        126 to "Cantan santos ángeles",
        127 to "Noche de luz",
        128 to "A medianoche se oyó",
        129 to "Oh, pueblecito de Belén",
        130 to "Escuchad el son triunfal",
        131 to "Asombro dio a los magos",
        132 to "La primera Navidad",
        133 to "Campanas de Navidad",
        134 to "En la Judea, en tierra de Dios",
        135 to "Hoy sembramos la semilla",
        136 to "Todos los santos",
        137 to "Tú me has dado muchas bendiciones, Dios",
        138 to "Señor, yo te seguiré",
        139 to "Ama el Pastor las ovejas",
        140 to "A Dios el Padre y a Jesús",
        141 to "¿En el mundo he hecho bien?",
        142 to "Otro año ha pasado",
        143 to "A Dios ofrecemos gozosa canción",
        144 to "A la gloria marcharemos",
        145 to "La voz, ya, del eterno",
        146 to "Tengo gozo en mi alma hoy",
        147 to "Recojamos los destellos",
        148 to "Si hay gozo en tu corazón",
        149 to "Trabajad con fervor",
        150 to "Siembra gozo",
        151 to "Oh, hablemos con tiernos acentos",
        152 to "No hablemos con enojo",
        153 to "Oíd el toque del clarín",
        154 to "Haz tú lo justo",
        155 to "Haz el bien",
        156 to "Señor del cielo, Jehová",
        157 to "Cuenta tus bendiciones",
        158 to "Trabajemos hoy en la obra",
        159 to "Con valor marchemos",
        160 to "Tu casa amamos, Dios",
        161 to "Llamados a servir",
        162 to "Somos los soldados",
        163 to "¡Mirad! Reales huestes",
        164 to "Pon tu hombro a la lid",
        165 to "Tu palabra",
        166 to "Firmes creced en la fe",
        167 to "A vencer",
        168 to "Juventud de Israel",
        169 to "Al mundo ve a predicar",
        170 to "¿Quién sigue al Señor?",
        171 to "La luz de la verdad",
        172 to "Cuando enseñe a Tus hijos",
        173 to "El fin se acerca",
        174 to "Qué maravillosas Tus obras",
        175 to "A donde me mandes iré",
        176 to "Palabras de amor",
        177 to "¿Qué es la verdad?",
        178 to "Nuestra mente se refleja",
        179 to "La barra de hierro",
        180 to "Al leer las Escrituras",
        181 to "Cuando raya el nuevo dia",
        182 to "Bienvenido, día santo",
        183 to "Santos templos de Sión",
        184 to "Id, oh santos, a los templos",
        185 to "En los postreros días",
        186 to "Volved vuestro corazón",
        187 to "Oh mi Padre",
        188 to "Quienes nos brindan su amor",
        189 to "Oh Padre, llénanos de amor",
        190 to "Hay un hogar eterno",
        191 to "Con maravillas obra Dios",
        192 to "¿Por qué somos?",
        193 to "El hogar es como el cielo",
        194 to "Cuando hay amor",
        195 to "Las familias pueden ser eternas",
        196 to "Soy un hijo de Dios",
        197 to "Siempre obedece los mandamientos",
        198 to "Hazme andar en la luz",
        199 to "Dios vive",
        200 to "La luz de Dios",
        201 to "Dios cuida a sus hijos",
        202 to "En el pueblo de Sión",
        203 to "Amad a otros",
        204 to "Hijos de nuestro Padre",
        205 to "Sirvamos unidas (Mujeres)",
        206 to "Venid, los que tenéis de Dios el sacerdocio (Hombres)",
        207 to "Oh vos que sois llamados (Hombres)",
        208 to "Brillan rayos de clemencia (Hombres)",
        209 to "Oh élderes de Israel (Hombres)",
        1001 to "Fuente de mis bendiciones",
        1002 to "Cuando vuelva el Salvador",
        1003 to "Reina paz en mi ser",
        1004 to "Andaré con Cristo",
        1005 to "Él cuida de las aves",
        1006 to "En tu corazón entona una canción",
        1007 to "En Ti pensamos",
        1008 to "Agua viva, pan de vida",
        1009 to "Getsemaní",
        1010 to "Sublime gracia",
        1011 to "Somos niños, de la mano del Señor",
        1012 to "En cualquier ocasión",
        1013 to "Dios me da Su gracia",
        1014 to "Mi buen pastor es Jehová",
        1015 to "Oh, cuán pleno, cuán profundo",
        1016 to "Mirad las marcas de Jesús",
        1017 to "El Cristo es",
        1018 to "Ven, oh, Cristo",
        1019 to "Amar igual que Tú",
        1020 to "Tiernamente Jesús hoy nos llama",
        1021 to "Cristo me ama, lo sé",
        1022 to "Con fe en cada paso",
        1023 to "Firme en las promesas",
        1024 to "Tengo fe en Jesús, mi Señor",
        1025 to "Hoy te doy mi corazón",
        1026 to "Lugares santos",
        1027 to "Soy bienvenido a Su hogar",
        1028 to "Mi pequeña luz",
        1029 to "Los dones que el Padre derrama",
        1030 to "Dios siempre cerca está",
        1031 to "Venid, oíd la voz de Cristo",
        1032 to "Mirad a Cristo",
        1033 to "Placentero nos es trabajar",
        1034 to "Soy pionero también",
        1035 to "Honraré Su día",
        1036 to "El Libro de Mormón leeré",
        1037 to "Vivir, servir, orar y cantar",
        1038 to "Es Jehová mi buen pastor",
        1039 to "Es gracias al Señor",
        1040 to "Prevalece Su voz",
        1041 to "Por mí la vida diste Tú",
        1042 to "Clemente Dios, hoy cual ayer",
        1043 to "Oh, Redentor, rogamos Tu perdón",
        1044 to "Así nos ministró Cristo",
        1045 to "La senda es Jesús",
        1046 to "¿Puedes tú contar los astros?",
        1047 to "Dios me conoce",
        1048 to "A Ti oramos",
        1049 to "José oró con fe",
        1050 to "Ven a mí",
        1051 to "Señor, un buen día es hoy",
        1052 to "¡Oh, qué gozo nos da!",
        1053 to "Mis convenios",
        1054 to "Al bautizarme a Cristo seguiré",
        1055 to "El poder del Santo Espíritu",
        1056 to "Elías y la suave voz",
        1057 to "Mi pastor es Cristo",
        1058 to "Mi canto en la noche",
        1059 to "El mundo es de Dios",
        1060 to "Un arca construiré",
        1061 to "Cuán dulce hogar de amor",
        1062 to "Nuestro ayuno, oh, Señor",
        1201 to "Gloria al día de redención",
        1202 to "El divino Jesús nació",
        1203 to "¿Qué niño es este?",
        1204 to "Estrella de luz",
        1205 to "En Pascua himnos entonad",
        1206 to "¿Viste tú?",
        1207 to "Paz, paz, paz",
        1208 to "¡Ve! Dilo en las montañas",
        1209 to "Pequeñito en pesebre",
        1210 to "Tiempo atrás, en un jardín"
    )

    fun getNombre(numero: Int): String {
        return lista[numero] ?: ""
    }
}