package com.example.agendasacramental

object HimnosEn {
    val himnos = mapOf(
        1 to "The Morning Breaks",
        2 to "The Spirit of God",
        3 to "Now Let Us Rejoice",
        4 to "Truth Eternal",
        5 to "High on the Mountain Top",
        6 to "Redeemer of Israel",
        7 to "Israel, Israel, God Is Calling",
        8 to "Awake and Arise",
        9 to "Come, Rejoice",
        10 to "Come, Sing to the Lord",
        11 to "What Was Witnessed in the Heavens?",
        12 to "’Twas Witnessed in the Morning Sky",
        13 to "An Angel from on High",
        14 to "Sweet Is the Peace the Gospel Brings",
        15 to "I Saw a Mighty Angel Fly",
        16 to "What Glorious Scenes Mine Eyes Behold",
        17 to "Awake, Ye Saints of God, Awake!",
        18 to "The Voice of God Again Is Heard",
        19 to "We Thank Thee, O God, for a Prophet",
        20 to "God of Power, God of Right",
        21 to "Come, Listen to a Prophet’s Voice",
        22 to "We Listen to a Prophet’s Voice",
        23 to "We Ever Pray for Thee",
        24 to "God Bless Our Prophet Dear",
        25 to "Now We’ll Sing with One Accord",
        26 to "Joseph Smith’s First Prayer",
        27 to "Praise to the Man",
        28 to "Saints, Behold How Great Jehovah",
        29 to "A Poor Wayfaring Man of Grief",
        30 to "Come, Come, Ye Saints",
        31 to "O God, Our Help in Ages Past",
        32 to "The Happy Day at Last Has Come",
        33 to "Our Mountain Home So Dear",
        34 to "O Ye Mountains High",
        35 to "For the Strength of the Hills",
        36 to "They, the Builders of the Nation",
        37 to "The Wintry Day, Descending to Its Close",
        38 to "Come, All Ye Saints of Zion",
        39 to "O Saints of Zion",
        40 to "Arise, O Glorious Zion",
        41 to "Let Zion in Her Beauty Rise",
        42 to "Hail to the Brightness of Zion’s Glad Morning!",
        43 to "Zion Stands with Hills Surrounded",
        44 to "Beautiful Zion, Built Above",
        45 to "Lead Me into Life Eternal",
        46 to "Glorious Things of Thee Are Spoken",
        47 to "We Will Sing of Zion",
        48 to "Glorious Things Are Sung of Zion",
        49 to "Adam-ondi-Ahman",
        50 to "Come, Thou Glorious Day of Promise",
        51 to "Sons of Michael, He Approaches",
        52 to "The Day Dawn Is Breaking",
        53 to "Let Earth’s Inhabitants Rejoice",
        54 to "Behold, the Mountain of the Lord",
        55 to "Lo, the Mighty God Appearing!",
        56 to "Softly Beams the Sacred Dawning",
        57 to "We’re Not Ashamed to Own Our Lord",
        58 to "Come, Ye Children of the Lord",
        59 to "Come, O Thou King of Kings",
        60 to "Battle Hymn of the Republic",
        61 to "Raise Your Voices to the Lord",
        62 to "All Creatures of Our God and King",
        63 to "Great King of Heaven",
        64 to "On This Day of Joy and Gladness",
        65 to "Come, All Ye Saints Who Dwell on Earth",
        66 to "Rejoice, the Lord Is King!",
        67 to "Glory to God on High",
        68 to "A Mighty Fortress Is Our God",
        69 to "All Glory, Laud, and Honor",
        70 to "Sing Praise to Him",
        71 to "With Songs of Praise",
        72 to "Praise to the Lord, the Almighty",
        73 to "Praise the Lord with Heart and Voice",
        74 to "Praise Ye the Lord",
        75 to "In Hymns of Praise",
        76 to "God of Our Fathers, We Come unto Thee",
        77 to "Great Is the Lord",
        78 to "God of Our Fathers, Whose Almighty Hand",
        79 to "With All the Power of Heart and Tongue",
        80 to "God of Our Fathers, Known of Old",
        81 to "Press Forward, Saints",
        82 to "For All the Saints",
        83 to "Guide Us, O Thou Great Jehovah",
        84 to "Faith of Our Fathers",
        85 to "How Firm a Foundation",
        86 to "How Great Thou Art",
        87 to "God Is Love",
        88 to "Great God, Attend While Zion Sings",
        89 to "The Lord Is My Light",
        90 to "From All That Dwell below the Skies",
        91 to "Father, Thy Children to Thee Now Raise",
        92 to "For the Beauty of the Earth",
        93 to "Prayer of Thanksgiving",
        94 to "Come, Ye Thankful People",
        95 to "Now Thank We All Our God",
        96 to "Dearest Children, God Is Near You",
        97 to "Lead, Kindly Light",
        98 to "I Need Thee Every Hour",
        99 to "Nearer, Dear Savior, to Thee",
        100 to "Nearer, My God, to Thee",
        101 to "Guide Me to Thee",
        102 to "Jesus, Lover of My Soul",
        103 to "Precious Savior, Dear Redeemer",
        104 to "Jesus, Savior, Pilot Me",
        105 to "Master, the Tempest Is Raging",
        106 to "God Speed the Right",
        107 to "Lord, Accept Our True Devotion",
        108 to "The Lord Is My Shepherd",
        109 to "The Lord My Pasture Will Prepare",
        110 to "Cast Thy Burden upon the Lord",
        111 to "Rock of Ages",
        112 to "Savior, Redeemer of My Soul",
        113 to "Our Savior’s Love",
        114 to "Come unto Him",
        115 to "Come, Ye Disconsolate",
        116 to "Come, Follow Me",
        117 to "Come unto Jesus",
        118 to "Ye Simple Souls Who Stray",
        119 to "Come, We That Love the Lord",
        120 to "Lean on My Ample Arm",
        121 to "I’m a Pilgrim, I’m a Stranger",
        122 to "Though Deepening Trials",
        123 to "Oh, May My Soul Commune with Thee",
        124 to "Be Still, My Soul",
        125 to "How Gentle God’s Commands",
        126 to "How Long, O Lord Most Holy and True",
        127 to "Does the Journey Seem Long?",
        128 to "When Faith Endures",
        129 to "Where Can I Turn for Peace?",
        130 to "Be Thou Humble",
        131 to "More Holiness Give Me",
        132 to "God Is in His Holy Temple",
        133 to "Father in Heaven",
        134 to "I Believe in Christ",
        135 to "My Redeemer Lives",
        136 to "I Know That My Redeemer Lives",
        137 to "Testimony",
        138 to "Bless Our Fast, We Pray",
        139 to "In Fasting We Approach Thee",
        140 to "Did You Think to Pray?",
        141 to "Jesus, the Very Thought of Thee",
        142 to "Sweet Hour of Prayer",
        143 to "Let the Holy Spirit Guide",
        144 to "Secret Prayer",
        145 to "Prayer Is the Soul’s Sincere Desire",
        146 to "Gently Raise the Sacred Strain",
        147 to "Sweet Is the Work",
        148 to "Sabbath Day",
        149 to "As the Dew from Heaven Distilling",
        150 to "O Thou Kind and Gracious Father",
        151 to "We Meet, Dear Lord",
        152 to "God Be with You Till We Meet Again",
        153 to "Lord, We Ask Thee Ere We Part",
        154 to "Father, This Hour Has Been One of Joy",
        155 to "We Have Partaken of Thy Love",
        156 to "Sing We Now at Parting",
        157 to "Thy Spirit, Lord, Has Stirred Our Souls",
        158 to "Before Thee, Lord, I Bow My Head",
        159 to "Now the Day Is Over",
        160 to "Softly Now the Light of Day",
        161 to "The Lord Be with Us",
        162 to "Lord, We Come before Thee Now",
        163 to "Lord, Dismiss Us with Thy Blessing",
        164 to "Great God, to Thee My Evening Song",
        165 to "Abide with Me; ’Tis Eventide",
        166 to "Abide with Me!",
        167 to "Come, Let Us Sing an Evening Hymn",
        168 to "As the Shadows Fall",
        169 to "As Now We Take the Sacrament",
        170 to "God, Our Father, Hear Us Pray",
        171 to "With Humble Heart",
        172 to "In Humility, Our Savior",
        173 to "While of These Emblems We Partake",
        174 to "While of These Emblems We Partake",
        175 to "O God, the Eternal Father",
        176 to "’Tis Sweet to Sing the Matchless Love",
        177 to "’Tis Sweet to Sing the Matchless Love",
        178 to "O Lord of Hosts",
        179 to "Again, Our Dear Redeeming Lord",
        180 to "Father in Heaven, We Do Believe",
        181 to "Jesus of Nazareth, Savior and King",
        182 to "We’ll Sing All Hail to Jesus’ Name",
        183 to "In Remembrance of Thy Suffering",
        184 to "Upon the Cross of Calvary",
        185 to "Reverently and Meekly Now",
        186 to "Again We Meet around the Board",
        187 to "God Loved Us, So He Sent His Son",
        188 to "Thy Will, O Lord, Be Done",
        189 to "O Thou, Before the World Began",
        190 to "In Memory of the Crucified",
        191 to "Behold the Great Redeemer Die",
        192 to "He Died! The Great Redeemer Died",
        193 to "I Stand All Amazed",
        194 to "There Is a Green Hill Far Away",
        195 to "How Great the Wisdom and the Love",
        196 to "Jesus, Once of Humble Birth",
        197 to "O Savior, Thou Who Wearest a Crown",
        198 to "That Easter Morn",
        199 to "He Is Risen!",
        200 to "Christ the Lord Is Risen Today",
        201 to "Joy to the World",
        202 to "Oh, Come, All Ye Faithful",
        203 to "Angels We Have Heard on High",
        204 to "Silent Night",
        205 to "Once in Royal David’s City",
        206 to "Away in a Manger",
        207 to "It Came upon the Midnight Clear",
        208 to "O Little Town of Bethlehem",
        209 to "Hark! The Herald Angels Sing",
        210 to "With Wondering Awe",
        211 to "While Shepherds Watched Their Flocks",
        212 to "Far, Far Away on Judea’s Plains",
        213 to "The First Noel",
        214 to "I Heard the Bells on Christmas Day",
        215 to "Ring Out, Wild Bells",
        216 to "We Are Sowing",
        217 to "Come, Let Us Anew",
        218 to "We Give Thee But Thine Own",
        219 to "Because I Have Been Given Much",
        220 to "Lord, I Would Follow Thee",
        221 to "Dear to the Heart of the Shepherd",
        222 to "Hear Thou Our Hymn, O Lord",
        223 to "Have I Done Any Good?",
        224 to "I Have Work Enough to Do",
        225 to "We Are Marching On to Glory",
        226 to "Improve the Shining Moments",
        227 to "There Is Sunshine in My Soul Today",
        228 to "You Can Make the Pathway Bright",
        229 to "Today, While the Sun Shines",
        230 to "Scatter Sunshine",
        231 to "Father, Cheer Our Souls Tonight",
        232 to "Let Us Oft Speak Kind Words",
        233 to "Nay, Speak No Ill",
        234 to "Jesus, Mighty King in Zion",
        235 to "Should You Feel Inclined to Censure",
        236 to "Lord, Accept into Thy Kingdom",
        237 to "Do What Is Right",
        238 to "Behold Thy Sons and Daughters, Lord",
        239 to "Choose the Right",
        240 to "Know This, That Every Soul Is Free",
        241 to "Count Your Blessings",
        242 to "Praise God, from Whom All Blessings Flow",
        243 to "Let Us All Press On",
        244 to "Come Along, Come Along",
        245 to "This House We Dedicate to Thee",
        246 to "Onward, Christian Soldiers",
        247 to "We Love Thy House, O God",
        248 to "Up, Awake, Ye Defenders of Zion",
        249 to "Called to Serve",
        250 to "We Are All Enlisted",
        251 to "Behold! A Royal Army",
        252 to "Put Your Shoulder to the Wheel",
        253 to "Like Ten Thousand Legions Marching",
        254 to "True to the Faith",
        255 to "Carry On",
        256 to "As Zion’s Youth in Latter Days",
        257 to "Rejoice! A Glorious Sound Is Heard",
        258 to "O Thou Rock of Our Salvation",
        259 to "Hope of Israel",
        260 to "Who’s on the Lord’s Side?",
        261 to "Thy Servants Are Prepared",
        262 to "Go, Ye Messengers of Glory",
        263 to "Go Forth with Faith",
        264 to "Hark, All Ye Nations!",
        265 to "Arise, O God, and Shine",
        266 to "The Time Is Far Spent",
        267 to "How Wondrous and Great",
        268 to "Come, All Whose Souls Are Lighted",
        269 to "Jehovah, Lord of Heaven and Earth",
        270 to "I’ll Go Where You Want Me to Go",
        271 to "Oh, Holy Words of Truth and Love",
        272 to "Oh Say, What Is Truth?",
        273 to "Truth Reflects upon Our Senses",
        274 to "The Iron Rod",
        275 to "Men Are That They Might Have Joy",
        276 to "Come Away to the Sunday School",
        277 to "As I Search the Holy Scriptures",
        278 to "Thanks for the Sabbath School",
        279 to "Thy Holy Word",
        280 to "Welcome, Welcome, Sabbath Morning",
        281 to "Help Me Teach with Inspiration",
        282 to "We Meet Again in Sabbath School",
        283 to "The Glorious Gospel Light Has Shone",
        284 to "If You Could Hie to Kolob",
        285 to "God Moves in a Mysterious Way",
        286 to "Oh, What Songs of the Heart",
        287 to "Rise, Ye Saints, and Temples Enter",
        288 to "How Beautiful Thy Temples, Lord",
        289 to "Holy Temples on Mount Zion",
        290 to "Rejoice, Ye Saints of Latter Days",
        291 to "Turn Your Hearts",
        292 to "O My Father",
        293 to "Each Life That Touches Ours for Good",
        294 to "Love at Home",
        295 to "O Love That Glorifies the Son",
        296 to "Our Father, by Whose Name",
        297 to "From Homes of Saints Glad Songs Arise",
        298 to "Home Can Be a Heaven on Earth",
        299 to "Children of Our Heavenly Father",
        300 to "Families Can Be Together Forever",
        301 to "I Am a Child of God",
        302 to "I Know My Father Lives",
        303 to "Keep the Commandments",
        304 to "Teach Me to Walk in the Light",
        305 to "The Light Divine",
        306 to "God’s Daily Care",
        307 to "In Our Lovely Deseret",
        308 to "Love One Another",
        309 to "As Sisters in Zion (Women)",
        310 to "A Key Was Turned in Latter Days (Women)",
        311 to "We Meet Again as Sisters (Women)",
        312 to "We Ever Pray for Thee (Women)",
        313 to "God Is Love (Women)",
        314 to "How Gentle God’s Commands (Women)",
        315 to "Jesus, the Very Thought of Thee (Women)",
        316 to "The Lord Is My Shepherd (Women)",
        317 to "Sweet Is the Work (Women)",
        318 to "Love at Home (Women)",
        319 to "Ye Elders of Israel (Men)",
        320 to "The Priesthood of Our Lord (Men)",
        321 to "Ye Who Are Called to Labor (Men)",
        322 to "Come, All Ye Sons of God (Men)",
        323 to "Rise Up, O Men of God (Men’s Choir)",
        324 to "Rise Up, O Men of God (Men)",
        325 to "See the Mighty Priesthood Gathered (Men’s Choir)",
        326 to "Come, Come, Ye Saints (Men’s Choir)",
        327 to "Go, Ye Messengers of Heaven (Men’s Choir)",
        328 to "An Angel from on High (Men’s Choir)",
        329 to "Thy Servants Are Prepared (Men’s Choir)",
        330 to "See, the Mighty Angel Flying (Men’s Choir)",
        331 to "Oh Say, What Is Truth? (Men’s Choir)",
        332 to "Come, O Thou King of Kings (Men’s Choir)",
        333 to "High on the Mountain Top (Men’s Choir)",
        334 to "I Need Thee Every Hour (Men’s Choir)",
        335 to "Brightly Beams Our Father’s Mercy (Men’s Choir)",
        336 to "School Thy Feelings (Men’s Choir)",
        337 to "O Home Beloved (Men’s Choir)",
        338 to "America the Beautiful",
        339 to "My Country, ’Tis of Thee",
        340 to "The Star-Spangled Banner",
        341 to "God Save the King",
        1001 to "Come, Thou Fount of Every Blessing",
        1002 to "When the Savior Comes Again",
        1003 to "It Is Well with My Soul",
        1004 to "I Will Walk with Jesus",
        1005 to "His Eye Is on the Sparrow",
        1006 to "Think a Sacred Song",
        1007 to "As Bread Is Broken",
        1008 to "Bread of Life, Living Water",
        1009 to "Gethsemane",
        1010 to "Amazing Grace",
        1011 to "Holding Hands Around the World",
        1012 to "Anytime, Anywhere",
        1013 to "God’s Gracious Love",
        1014 to "My Shepherd Will Supply My Need",
        1015 to "Oh, the Deep, Deep Love of Jesus",
        1016 to "Behold the Wounds in Jesus’ Hands",
        1017 to "This Is the Christ",
        1018 to "Come, Lord Jesus",
        1019 to "To Love like Thee",
        1020 to "Softly and Tenderly Jesus Is Calling",
        1021 to "I Know That My Savior Loves Me",
        1022 to "Faith in Every Footstep",
        1023 to "Standing on the Promises",
        1024 to "I Have Faith in the Lord Jesus Christ",
        1025 to "Take My Heart and Let It Be Consecrated",
        1026 to "Holy Places",
        1027 to "Welcome Home",
        1028 to "This Little Light of Mine",
        1029 to "I Can’t Count Them All",
        1030 to "Close as a Quiet Prayer",
        1031 to "Come, Hear the Word the Lord Has Spoken",
        1032 to "Look unto Christ",
        1033 to "Oh, How Great Is Our Joy",
        1034 to "I’m a Pioneer Too",
        1035 to "As I Keep the Sabbath Day",
        1036 to "Read the Book of Mormon and Pray",
        1037 to "I’m Gonna Live So God Can Use Me",
        1038 to "The Lord’s My Shepherd",
        1039 to "Because",
        1040 to "His Voice as the Sound",
        1041 to "O Lord, Who Gave Thy Life for Me",
        1042 to "Thou Gracious God, Whose Mercy Lends",
        1043 to "Help Us Remember",
        1044 to "How Did the Savior Minister?",
        1045 to "Jesus Is the Way",
        1046 to "Can You Count the Stars in Heaven?",
        1047 to "He Cares for Me",
        1048 to "Our Prayer to Thee",
        1049 to "Joseph Prayed in Faith",
        1050 to "Stand by Me",
        1051 to "This Day Is a Good Day, Lord",
        1052 to "Joyfully Bound",
        1053 to "My Covenants",
        1054 to "When I Am Baptized",
        1055 to "The Power of the Holy Ghost",
        1056 to "Elijah and the Still, Small Voice",
        1057 to "Jesus Is My Shepherd",
        1058 to "My Song in the Night",
        1059 to "This Is My Father’s World",
        1060 to "Build an Ark",
        1061 to "Love Will Bless Our Home",
        1062 to "Lord, Accept Our Humble Fast",
        1201 to "Hail the Day That Sees Him Rise",
        1202 to "He Is Born, the Divine Christ Child",
        1203 to "What Child Is This?",
        1204 to "Star Bright",
        1205 to "Let Easter Anthems Ring",
        1206 to "Were You There?",
        1207 to "Still, Still, Still",
        1208 to "Go Tell It on the Mountain",
        1209 to "Little Baby in a Manger",
        1210 to "Long Ago, Within a Garden",
    )

    fun getNombre(numero: Int): String {
        return himnos[numero] ?: ""
    }
}